### ISSUE TITLE
Insight Seg Fault

### ISSUE THREAD

**Issue by tmd3vt** [trueos/lumina#330] opened 2016-12-21 22:50 UTC
I am using Lumina 1.1 on FreeBSD 11 and the file manager crashes when I go into specific folders on a compressed ZFS file system on an external USB hard drive.  I get this message when changing between folders:

Load Dir: "/"
QKqueueFileSystemWatcherEngine::addPaths: open: No such file or directory

But it doesn't crash unless I go deep into the file system with the large Olympus raw files .ORP.  If the folders have only jpegs all is fine.  On a local solid state drive all is well so I am wondering if it is a speed issue?

**Comment by beanpole135** [comment] 2016-12-27 15:55
Ok, I am doing some checking on this right now with Lumina 1.1.2 on TrueOS, and cannot reproduce the issue so far. 
I went online and downloaded a sample .ORF file to see if it was something about that format in particular, but the file is not recognized as an image format by Qt (on my system at least), so the file size/format itself does not appear to be an issue because Insight does not load the full image to show a thumbnail (it just uses the default "unknown" mimetype image).
That seems to narrow it down to something related to the USB connection and/or how many threads the file manager is spinning up to probe the files. Do you have an idea of the number of files in that directory? I could try running some stress tests here with large collections of files and see if I can reproduce it then.

**Comment by tmd3vt** [comment] 2016-12-27 18:31
There are well around 300 files in the folder, and it has subfolders with probably the same number of files though they are not raw files. Some large tiffs and jpegs. I hope this helps. I am away from my computer at the moment, but I can run some tests next week. Thank you!

**Comment by beanpole135** [comment] 2016-12-28 13:17
300 files should be no problem - I regularly have to browse icon theme directories which have 600+ PNG files in them (so each file has to get loaded in order to show thumbnails) and I don't have any issues with it.

**Comment by tmd3vt** [comment] 2017-01-02 22:25
It seems to be related to the compressed ZFS folder I have on that drive.
The same files in an uncompressed folder on the same drive do not crash
lumina-fm.  I copied all the files over to an uncompressed folder on the
same drive and all was well.

**Comment by tmd3vt** [comment] 2017-01-03 01:46
I upgraded to 1.1.0 using ports.  I was using 1.0 in the form of the pkg.
All is well now too.

**Comment by q5sys** [comment] 2017-01-03 02:21
Thanks for reporting back, I'm glad it's working for you now.  I'll go ahead and close this ticket.  If you have other problems, please let us know.

**Closed by q5sys** 2017-01-03 02:21 UTC
