### ISSUE TITLE
Panel-performance: Icons of applications launchers take too long

### ISSUE THREAD

**Issue by utrenkner** [trueos/lumina#376] opened 2017-02-10 09:49 UTC
When I have several programs open, the application launcher icons take some time to appear. This can get really annoying, because then all the open programs shown in the panel are moved to make space for the icons. Thus, several times every day, I click on another open program in the panel only to have it shifted and another program is brought to the front.

Maybe the problem is caused by the same thing that causes my [File Manager to be so slow](https://github.com/trueos/lumina/issues/358).

I will keep watching what is going on with Lumina - and be happy to compile and test new versions. But for day-to-day use, this DE is unfortunately not yet ready. At least not on my T530. I will have to look for something else.

This is really sad, but it confirms what I and many others who commented on PC-BSD/TrueOS/Lumina in various threads on the German bsdforen.de have experienced: This OS and its components never seem to become really stable. Whenever something is 90% done, it seems the project jumps on yet another new idea (be it SysAdm, Wayland integration or whatever). Contrary to what has been a PC-BSD goal for a long time, this OS and its components should not be recommended to beginners. Too much of it seems to be in Beta-state and constantly changing.

Sorry for this rant. But it is the 3rd time I thoroghly tried PC-BSD (twice) and Lumina (since spring of 2016). I give up. Again.

**Comment by beanpole135** [comment] 2017-02-13 16:29
Where exactly is the slowdown?
A) Launching an app to when the app window appears
B) App window appearance to when the task manager button for that window shows up.

Additionally, which task manager plugin are you using (grouped/ungrouped), and approximately how many windows do you have open before this starts to happen? The output of "top" might be helpful in this situation too -  simply to see if your system is just running out of available resources.

I use TrueOS/Lumina on my Lenovo T420 here and cannot reproduce the slowness issues you have mentioned here or on the other file manager ticket - so any information you can provide will be very useful. My gut feeling though is that it is something specific to either your hardware or your system settings which is creating the bottleneck.

**Comment by utrenkner** [comment] 2017-02-14 16:27
Thanks for the reply. I just sent you a short video (ca. 20 seconds) which shows the delay in the panel.

**Comment by Mrt134** [comment] 2017-08-14 14:03
This appears to have been resolved with icon caching improvements and other Lumina fixes in the versions released after this ticket was created. Please reopen or create a new issue if this problem occurs again.

**Closed by Mrt134** 2017-08-14 14:03 UTC
Labels: status:investigation
