### ISSUE TITLE
Lumina 1.0 does not start anymore (xinit  connection to server lost)

### ISSUE THREAD

**Issue by david8001** [trueos/lumina#280] opened 2016-10-03 11:13 UTC
Hi,

Under Lumina 0.9 / Freebsd 11.0RC3with DELL Latitude 510m everything worked fine.
After the upgrade to Lumina 1.0 the start-lumina-desktop behave in an not proper way. 
X session get just closed with the notice "xinit connection to server lost"

After some digging it seems now that the new start-lumina-desktop get confused by the presence of the 2 displays (internal and external (which is not connected)). The internal is on the PCI Intel:0:2:0 and the external is on the PCI:0:2:1. 

I did not change the xorg.conf file which define the screen on Intel:0:2:0.

Is there some workaround or new settings must be taken into account with this version?

Regards,

David

**Comment by beanpole135** [comment] 2016-10-03 13:36
Monitor settings should not crash/close Lumina at all, since that is a completely separate subsystem which does not touch the main session. 
How are you starting Lumina? (I am guessing that you are running "start-lumina-desktop" from the CLI after logging in).
Do you have `dbus_enable="YES"` within your /etc/rc.conf ? There is a bug within Qt right now that requires a dbus session to be available otherwise the Qt libraries will crash. If you don't want to have a dbus session running as root, you can start lumina via `dbus-launch --exit-with-session start-lumina-desktop` instead, which will only startup a local/user dbus session and allows Qt to function again.

**Comment by david8001** [comment] 2016-10-03 13:45
Same behavior when I lunch it within .xinitrc (exec start-lumina-desktop) or with CLI 
dbus-enable is set to YES
Same behavior if I start it as root or as a standard user.
I did not change any settings which worked with version 0.9

**Comment by DmitryPostolov** [comment] 2016-10-04 03:54
Sorry for my bad English... On my nettops Intel NUCs Lumina 1.0 dont works on FreeBSD (scfb) with commands "start-lumina-desktop" (CLI), but Lumina works fine, if to add dbus in /etc/rc.conf and to create file, for example: ./lumi in user home directory:

`#!/bin/sh
exec xinit /usr/local/bin/start-lumina-desktop`

And after Run: > ./lumi Lumina works fine only with xinit string.

**Comment by david8001** [comment] 2016-10-04 08:41
Thank you Dmitry!! It worked that way. 
It should be nice to modify the "start-lumina-desktop" so that Lumina can start the usual way as every other DE and as it was before with version 0.9 :)

**Comment by mmcc1** [comment] 2016-10-06 16:36
I'm observing this in 0.9.0.1 on OpenBSD.  The default install is fine, but if a custom luminaDesktop.conf is provided, the program crashes out at this point:
`
if(setTheme){ LTHEME::setCurrentSettings( themesettings[0], themesettings[1], themesettings[2], themesettings[3], themesettings[4]); }
  LUtils::writeFile(setdir+"/sessionsettings.conf", sesset, true);
  LUtils::writeFile(setdir+"/desktopsettings.conf", deskset, true);
LUtils::writeFile(setdir+"/lumina-open.conf", lopenset, true);
`
void LUtils::LoadSystemDefaults(bool skipOS)
https://github.com/mmcc1/lumina/blob/v0.9.0-Release-p1/src-qt5/core/libLumina/LuminaUtils.cpp

The theme gets written correctly to ./lumina under the user account, but for some unidentified reason it then drops out to the console with "xinit connection to server lost".

**Comment by mmcc1** [comment] 2016-10-06 17:05
There appears to be a simple fix for 0.9.0.1 under OpenBSD and its creating a machine-id.  This is the command (the machine-id may be located elsewhere on other platforms):

dbus-uuidgen > /etc/machine-id

I will test this on a fresh install to confirm.

**Comment by mmcc1** [comment] 2016-10-06 19:36
Confirmed for 0.9.0.1 under OpenBSD 6.0.  Run this as root:

dbus-uuidgen > /etc/machine-id

**Comment by beanpole135** [comment] 2016-10-11 12:49
This should be fixed now. I also put a quick detection/fix for the DBUS/Qt bug into the start-lumina-desktop binary so that it will automatically apply the user-level workaround when launching the session (dbus-launch --exit-with-session lumina-desktop)

**Closed by beanpole135** 2016-10-11 12:49 UTC
