### ISSUE TITLE
Wallpaper Issues on a 4k Screen. (Qt 5.6 issue?)

### ISSUE THREAD

**Issue by Somnium42** [trueos/lumina#284] opened 2016-10-10 15:44 UTC
Hello.
Im currently using Lumina on Void linux to see how this DE fares against others on 4k resolution.
While most Things do work flawless (e.g no tearing during Full screen videos, even without xcompmgr) Wallpapers do not.
Using wallpaper on 4k resolution leads to strange tiling issues. It doesn't matter if you use Automatic-, Fullscreen-, Fit Screen- or Center-Layout it always looks the same
![4kwp](https://cloud.githubusercontent.com/assets/15572960/19241854/d13e988e-8f10-11e6-87d5-18e55c497a74.jpg)

1080p Wallper on 4k resolution is having a similar problem.
Tiled Layout
![1080ptiled](https://cloud.githubusercontent.com/assets/15572960/19241861/dc004772-8f10-11e6-9925-d7bf9cbcb333.jpg)

Automatic/Fullscreen Layout
![standartwp](https://cloud.githubusercontent.com/assets/15572960/19241862/dc198ad4-8f10-11e6-92e2-afefc56eba78.jpg)

On FullHD resolution everything works as expected.

I will close this issue should it turn out to be a Voild linux PKG related problem.

Tested on:
Lumina 1.0
Fluxbox 1.3.7_2
Nvidia closed source driver.

best Regards

**Comment by q5sys** [comment] 2016-10-10 16:03
Two questions... 1) What version of X are you running?  2) Can you find out
when the Void package team grabbed the Lumina sources from github so we can
try to figure out what commit it is using.
We just recently saw this crop up and we're trying to track down the
cause.  If it's happening on both Linux and BSD, that may help us track
down the issue.

**Comment by Somnium42** [comment] 2016-10-10 16:31
I just did a reboot with the 1080 wallpaper still active, this also leads to de desktop widgets being displayed on the wrong place 
![1080p](https://cloud.githubusercontent.com/assets/15572960/19242770/ecee0e58-8f14-11e6-950c-456ebaa01725.jpg)

Xorg -version
X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
According to https://github.com/voidlinux/void-packages/tree/d19eefb899eb023fc7d8ae28860579f5ba690f56/srcpkgs/lumina on August 9th. But im not sure if this is the right way to find out when they grabbed the sources since they could actually use the newest ones and only the template got changed 2 months ago.

**Comment by Somnium42** [comment] 2016-10-10 16:39
Not sure if This could be connected but if i look at the User agent of my browser it says:
Screen Resolution:	2258px x 1270px
Browser Window Size:	2243 px x 1181 px

This is bogus, the actual resolution if Ofc 3840X2160.
According to the screenshot, the second tile begins at pixel 2050, maybe something is reporting the wrong resolution?
Im going to try it on an different DE and look at the user Agent then

**Comment by q5sys** [comment] 2016-10-10 16:46
Thanks for the info. Initially I thought it was something on the BSD OS
side, but with it showing up in Linux as well that means it has to be
something that's similar between both.  So that narrows down the
possibilities of what it could be.

**Comment by beanpole135** [comment] 2016-10-11 12:45
@Somnium42 : Which version of Qt do you happen to be using on Void Linux? 

I am looking into this same issue right now, and it almost seems to be something in Qt 5.6 (at least on FreeBSD), since that is the only thing that changed recently and the wallpaper *used* to paint just find on 4K+ monitors with Qt 5.5.1.

**Comment by Somnium42** [comment] 2016-10-11 13:53
Void is using qt5-5.6.1_3.

**Comment by Somnium42** [comment] 2016-10-11 14:21
Just installed LXQT to check if it also has similar problems and yes it has.
Using the same qt version in lxqt leads to the same thing but if you mark with your mouse it reveales the fullsize wallpaper under the 2nd tile that is starting until you open a window/wait a few secounds.
![lxqtmouse4k](https://cloud.githubusercontent.com/assets/15572960/19273830/46cfb192-8fce-11e6-9355-bd6f45406376.jpg)

**Comment by beanpole135** [comment] 2016-10-11 14:33
I reproduced the painting issue where you can "uncover" the real wallpaper underneath the tiled image within Lumina by moving a desktop plugin around on desktop.

I think we have to chalk this one up as a bug in Qt 5.6, but I will keep looking around for a "bypass" for the issue if possible.

**Comment by q5sys** [comment] 2017-01-19 21:54
Since we've determined that this is a QT issue, I'm going to close the issue as it's out of our hands.

**Closed by q5sys** 2017-01-19 21:54 UTC
