### ISSUE TITLE
String that are not translated

### ISSUE THREAD

**Issue by scootergrisen** [trueos/lumina#389] opened 2017-02-24 17:04 UTC
Here i will write when i see strings that are not translated in Lumina.

When Lumina starts i see a sort of dialog with the title "Starting the Lumina Desktop..." and a quote.
The title and the quotes is showed in english even though i have translated the strings in the desktop ts file.

The system monitor have some translations in the desktop ts file but also says "degrees C", "r/s", "w/s" which does not have translations.

Under desktop settings we have a category called "System Settings" but both the title and all the items in the category appears in english, but i'm pretty sure its is translated. So please make sure to use the correct translations.

"No panels" don't see to be translatable. Under desktop settings - panels.

**Comment by scootergrisen** [comment] 2017-02-24 17:25
If i hover the curson on workspace plugin icon in the panel the tooltip says "Workspace 1" in english even though its translated if i click the icon.

**Comment by scootergrisen** [comment] 2017-02-26 00:43
It seems like common button names like "OK" "Cancel" etc. are not translated.
Should these translations come from qtbase perhaps?

**Comment by ZackaryWelch** [comment] 2017-08-15 19:50
The issue with the Boot Splash UI was caused by translations being loaded after the widget was created. This has been fixed, and the title and quotes are now translated. The system monitor isn't fully implemented yet, but when it is those strings should be translatable. The No Panels option is hardcoded, however a fix is in progress to make it translatable. The hover over the workspace icon works for me. OK and Cancel, as well as buttons in the file dialogue, are a part of Qt itself, however with a couple of lines they can be set to be translated as well.

**Comment by ZackaryWelch** [comment] 2017-09-07 22:26
System Settings and the pages below it have not been set to be translated yet. I'll look into the system monitor. The workspace tooltips are hardcoded. I'll work to set those to be translated. Thanks for noticing these issues! If you see anymore strings that aren't being translated, please let us know.

**Comment by ZackaryWelch** [comment] 2017-09-11 23:18
While I did find some strings in the system monitor that weren't set to be translated, the "r/s" and "w/s" are part of the return from iostat and cannot be translated. The System Settings page had a bug where it didn't translate the names in the desktop files. That has been fixed. I will now close this ticket as I have either fixed an issue you found or could not reproduce it. If you notice any more issues, please let us know. Thanks!

**Closed by ZackaryWelch** 2017-09-11 23:18 UTC
Labels: status:in_progress, Type:enhancement
