### ISSUE TITLE
Monitor configuration does not pick up external monitor after reboot (regression from 0.9)

### ISSUE THREAD

**Issue by utrenkner** [trueos/lumina#274] opened 2016-09-26 07:49 UTC
I use Lumina from the official FreeBSD repo (lumina-1.0.0.r.p1,2) on FreeBSD 11.0-RC3.

Somewhere around the launch of Lumina 1.0) the monitor configuration kind of broke and has not changed since: After a new boot of my Laptop, I start Lumina via `startx` (with  ~/.xinitrc containing only the line `exec start-lumina-desktop`). The monitor configuration only discovers the built-in monitor of the ThinkPad T530. I can manually add the external monitor, which is plugged into the docking station. But that freezes the scree. I have to kill the Xorg-Server and do another `startx`. Now the external monitor shows up in the configuration utility.

In Lumina 0.9, this had always worked flawlessly. 

Is there a ways to make Lumina permanently detect the external monitor? And if so, could I even use it automatically as my only screen if present?

**Comment by utrenkner** [comment] 2016-09-26 13:35
I checked again and have to slightly revise the bug report: X does not freeze. But when enabling the second screen it seems to add it alongside the other. The configuration tool has then moved on the other screen where I cannot use it anymore. There is no panel and I cannot really do anything. Therefore it looked frozen and I have to kill and restart the X server.

Any tip for how to deal with this? Doubling the sequence of startx and configuration of the screen is somewhat annoying - especially as it worked pre-1.0. Since I usually do it only once in the morning it is still bearable, but I was seriously considering installing Gnome again.

**Comment by utrenkner** [comment] 2016-10-03 09:24
No solution but I found a work-around: I have to move the monitor configuration window halfway over the side of the window, then click "enable screen" to have also the external monitor show up and be able to pick up the window, half of which is now available on the other side of the screen.

Ideally, the configuration should automatically pick up the external monitor.

Or else, it would be helpful, if there was the option to have the screens overlap (the smaller laptop screen being a part of the larger external screen). At the moment, I can only chose to enable the second monitor right or left of the built-in screen.

**Comment by beanpole135** [comment] 2016-10-11 14:12
I am getting ready for a large update to the screen configuration/setup utility here soon.... it needs a lot of things added/tweaked with it right now.


FYI: If you remove your ~/.config/lumina-desktop/lumina-xconfig.conf file, then Lumina will not try to adjust your  X screen layout on login, and instead just use whatever you have setup in your Xorg config and/or was auto-detected and enable by X. That config file *does* get automatically created/updated whenever you launch lumina-xconfig though, so just be aware of that.

**Comment by utrenkner** [comment] 2016-10-26 09:27
Short update: The problem exists also in Lumina 1.1.0p1

**Comment by q5sys** [comment] 2016-12-16 18:20
Not to sound like a broken record, but can you try this again with the latest source?  I did some testing the other day and i couldnt reproduce this issue.  I'm curious if its tied to something specific related to the hardware you have.

**Comment by utrenkner** [comment] 2016-12-22 09:49
@q5sys Thank you very much for continuing the effort.

I first had to solve some issues on my Laptop due to FreeBSD's current port mess with the change of jpeg libraries (currently, one cannot have both, Lumina and e.g. Firefox!). As I do not want to build everything myself (with beasts such as Libreoffice, Chromium,...), I chose to "downgrade" to FreeBSD's quarterly repo.

Based on that, I now built Lumina from the latest sources (fdaac67). The main problem remains: When I first log in, only the internal monitor of the laptop shows up. I have to add the second one, then delete the first one to use only my external monitor. This is the workflow in three screenshots:

![1](https://cloud.githubusercontent.com/assets/8254715/21421490/85fd9b20-c833-11e6-8f5b-e5f4c8a90e82.png)

![2](https://cloud.githubusercontent.com/assets/8254715/21421494/8b745e68-c833-11e6-8ab3-6dec69088f8d.png)

![3](https://cloud.githubusercontent.com/assets/8254715/21421500/91343b84-c833-11e6-8115-a212a0274507.png)

What has improved, though: When I delete the (smaller) internal monitor, the background image is scaled to the larger external monitor size. Before that, I always had to adjust it, as it would start to repeat at the bottom, where the internal monitor ended.

Even if I could not have the external screen automatically configured, when the laptop is in the docking station, it would help if you could give me a tip on how to script the changes that I have to do through Lumina's Screen Configuration tool (i.e. add second screen, delete first one).

**Comment by danboid** [comment] 2017-05-29 10:46
This is still a issue under the latest lumina in that I have to re-add my external monitor after every reboot. Ideally, lumina would remember and auto-restore your last used display config or otherwise it would be nice if it gave you the option to launch the display config tool when it detects a new display.

I have a similar issue under MATE in that I have to launch the MATE display config tool before my external monitor gets activated, after a reboot. I don't need to change any settings, just open the MATE display tool and wait a few seconds then it restores my previous settings for that external display.

**Comment by q5sys** [comment] 2017-07-23 13:20
Currently, Lumina does remember and use the previously used config.  When I'm in the Tennessee office, I plop my laptop down on my docking station and power on and both of my external monitors work instantly.  Once I have them set, when I shutdown and restart, Lumina remembers the config of them and boots up with them properly.

@utrenkner Are you still having this problem on your machine?

**Comment by Mrt134** [comment] 2017-09-07 14:46
[Lumina xconfig](https://github.com/trueos/lumina/commits/master/src-qt5/core-utils/lumina-xconfig) has been reworked and updated with many commits since the last action on this ticket. Since no one has updated to report the problem persists, I'm going to close this.
If this is still a problem or comes up again, please comment or reopen the ticket. Thanks!

**Closed by Mrt134** 2017-09-07 14:46 UTC
Labels: info:question, status:investigation

**Comment by danboid** [comment] 2017-09-07 18:06
Hi Tim!

Is the new Lumina xconfig in the latest dev images / the UNSTABLE repo yet?

**Comment by Mrt134** [comment] 2017-09-07 18:12
I believe the majority of the work is available with the latest UNSTABLE update. Some of the updates may be waiting for the next full UNSTABLE build, which will be forthcoming as soon as we finish up some server maintenance/work in the office.
