### ISSUE TITLE
Windows are no longer movable by dragging the title bar, and Alt-Tab does not switch

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#366] opened 2017-01-28 06:55 UTC
… and it's generally difficult to bring some types of window to the front. For example, whilst typing this in Firefox there's a window of Konsole to one side. Clicking in the content area is recognised (I can, for example select text) but the window does not come to the front. A click on the title bar has the required effect. Lumina Desktop Information may be less bugged. When that's in front, clicks in content areas of Firefox and Konsole windows fail to bring those applications to front. If I click the title bar of Firefox to bring it to the front, then clicks in various parts of Lumina Desktop Information do have the required effect; sensitivity is not limited to its title bar. 

I have encountered the immovable symptom on a few occasions, we should probably have an issue for tracking. 

## Environment

Lumina 1.2.1 on an HP EliteBook 850 G2. 

```
$ about
  ______                   ____  _____
 /_  __/______  _____     / __ \/ ___/ 
  / / / ___/ / / / _ \   / / / /\__ \ 
 / / / /  / /_/ /  __/  / /_/ /___/ / 
/_/ /_/   \__,_/\___/   \____//____/  

General info:
       Host:...............momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk
       User:...............grahamperrin
       Uptime:.............8 mins
       FreeBSD kernel ver:.12.0-CURRENT
       FreeBSD world ver:..12.0-CURRENT
       FreeBSD git branch:.drm-next
       FreeBSD git rev:....3dbce2a
       TrueOS ver:.........TrueOS-Desktop-201701261715
       Arch:...............amd64
       Kernel ident:.......GENERIC
       Bootloader:.........BSD
       Bootloader type:....EFI
       CPU:................Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
       CPU cores:..........4
       Memory (free/avail):13529 / 16384 Mb
       Package set:........CUSTOM
       Desktop environment:Lumina
       X11 Driver:.........modesetting_drv.so 
       OSS Driver:.........pcm1: <Realtek (0x0280) (Analog 2.0+HP/2.0)> (play/rec) default
       WIFI Driver:........iwm0
$ 
```

```
$ pciconf -lv
hostb0@pci0:0:0:0:      class=0x060000 card=0x2216103c chip=0x16048086 rev=0x09 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Broadwell-U Host Bridge -OPI'
    class      = bridge
    subclass   = HOST-PCI
vgapci0@pci0:0:2:0:     class=0x030000 card=0x2216103c chip=0x16168086 rev=0x09 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'HD Graphics 5500'
    class      = display                                                                                                               
    subclass   = VGA                                                                                                                   
hdac0@pci0:0:3:0:       class=0x040300 card=0x2216103c chip=0x160c8086 rev=0x09 hdr=0x00                                               
    vendor     = 'Intel Corporation'                                                                                                   
    device     = 'Broadwell-U Audio Controller'                                                                                        
    class      = multimedia                                                                                                            
    subclass   = HDA                                                                                                                   
xhci0@pci0:0:20:0:      class=0x0c0330 card=0x2216103c chip=0x9cb18086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Wildcat Point-LP USB xHCI Controller'
    class      = serial bus
    subclass   = USB
none0@pci0:0:22:0:      class=0x078000 card=0x2216103c chip=0x9cba8086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Wildcat Point-LP MEI Controller'
    class      = simple comms
em0@pci0:0:25:0:        class=0x020000 card=0x2216103c chip=0x15a28086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Ethernet Connection (3) I218-LM'
    class      = network
    subclass   = ethernet
hdac1@pci0:0:27:0:      class=0x040300 card=0x2216103c chip=0x9ca08086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Wildcat Point-LP High Definition Audio Controller'
    class      = multimedia
    subclass   = HDA
pcib1@pci0:0:28:0:      class=0x060400 card=0x2216103c chip=0x9c908086 rev=0xe3 hdr=0x01
    vendor     = 'Intel Corporation'
    device     = 'Wildcat Point-LP PCI Express Root Port'
    class      = bridge
    subclass   = PCI-PCI
pcib2@pci0:0:28:3:      class=0x060400 card=0x2216103c chip=0x9c968086 rev=0xe3 hdr=0x01
    vendor     = 'Intel Corporation'
    device     = 'Wildcat Point-LP PCI Express Root Port'
    class      = bridge
    subclass   = PCI-PCI
ehci0@pci0:0:29:0:      class=0x0c0320 card=0x2216103c chip=0x9ca68086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Wildcat Point-LP USB EHCI Controller'
    class      = serial bus
    subclass   = USB
isab0@pci0:0:31:0:      class=0x060100 card=0x2216103c chip=0x9cc38086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Wildcat Point-LP LPC Controller'
    class      = bridge
    subclass   = PCI-ISA
ahci0@pci0:0:31:2:      class=0x010601 card=0x2216103c chip=0x9c838086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Wildcat Point-LP SATA Controller [AHCI Mode]'
    class      = mass storage
    subclass   = SATA
none1@pci0:0:31:3:      class=0x0c0500 card=0x2216103c chip=0x9ca28086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Wildcat Point-LP SMBus Controller'
    class      = serial bus
    subclass   = SMBus
iwm0@pci0:2:0:0:        class=0x028000 card=0x50008086 chip=0x095a8086 rev=0x48 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Wireless 7265'
    class      = network
$ 
```

**Comment by grahamperrin** [comment] 2017-01-28 07:43
> Alt-Tab does not switch

... and Alt-F2 is set to launch lumina-search but no longer does so, and so on. I don't know whether those symptoms have the same root cause but the absence of keyboard-based switching does make it difficult to work around this problem. Also no longer working: Alt-Right-Click and drag to resize windows. 

----

Reproducible with the most recent Lumina on an earlier version of TrueOS Desktop: 

```
$ date ; uname -v
Sat 28 Jan 2017 07:37:49 GMT
FreeBSD 12.0-CURRENT #14 f92c24b(drm-next-4.7): Fri Jan  6 19:28:21 UTC 2017     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
$ about
  ______                   ____  _____
 /_  __/______  _____     / __ \/ ___/ 
  / / / ___/ / / / _ \   / / / /\__ \ 
 / / / /  / /_/ /  __/  / /_/ /___/ / 
/_/ /_/   \__,_/\___/   \____//____/  

General info:
       Host:...............momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk
       User:...............grahamperrin
       Uptime:.............29 mins
       FreeBSD kernel ver:.12.0-CURRENT
       FreeBSD world ver:..12.0-CURRENT
       TrueOS ver:.........TrueOS-DESKTOP-201701060022
       Arch:...............amd64
       Kernel ident:.......GENERIC
       CPU:................Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
       CPU cores:..........4
       Memory (free/avail):12909 / 16384 Mb
       Package set:........CUSTOM

Network IPV4 address: 
ifconfig: unable to get VHT configuration information: Invalid argument
       193.62.168.100
       127.0.0.1
       192.168.1.7

System components:
       TrueOS CLI:...r201701060022
       TrueOS UI:....r201701060022

$ pkg info lumina-desktop
pkg-static: No package(s) matching lumina-desktop
$ pkg info lumina
lumina-201701060022,2
Name           : lumina
Version        : 201701060022,2
Installed on   : Fri Jan  6 02:38:31 2017 GMT
Origin         : x11/lumina
Architecture   : freebsd:12:x86:64
Prefix         : /usr/local
Categories     : x11
Licenses       : BSD3CLAUSE
Maintainer     : kmoore@FreeBSD.org
WWW            : http://lumina-desktop.org
Comment        : Lumina Desktop Environment
Options        :
        I18N           : on
        MULTIMEDIA     : on
        TRUEOS         : on
Shared Libs required:
        libxcb-composite.so.0
        libxcb-damage.so.0
        libQt5X11Extras.so.5
        libQt5Gui.so.5
        libQt5Core.so.5
        libxcb-ewmh.so.2
        libGL.so.1
        libXdamage.so.1
        libxcb-image.so.0
        libQt5Concurrent.so.5
        libQt5Widgets.so.5
        libxcb-util.so.1
        libQt5Network.so.5
        libxcb-icccm.so.4
        libQt5Multimedia.so.5
        libQt5Svg.so.5
        libxcb.so.1
        libQt5MultimediaWidgets.so.5
        libxcb-xinput.so.0
Annotations    :
        repo_type      : binary
        repository     : trueos-major
Flat size      : 34.7MiB
Description    :
...
$ 
```

**Comment by beanpole135** [comment] 2017-01-30 12:56
This is indicative of the WM (fluxbox) not running.

Please ensure that the fluxbox package is still installed on your systems, and that you have not tried to manually change the WM that Lumina starts up for you (`~/.config/lumina-desktop/sessionsettings.conf`: Look for a "WindowManager=" option).

**Comment by beanpole135** [comment] 2017-01-30 13:13
Another thought: 
Which command was used to start up Lumina? It needs to be the "start-lumina-desktop" binary, and *not* the "lumina-desktop" binary.

**Comment by grahamperrin** [comment] 2017-02-01 01:43
```
$ date ; uname -v ; uname -n
Wed  1 Feb 2017 01:39:57 GMT
FreeBSD 12.0-CURRENT #14 f92c24b(drm-next-4.7): Fri Jan  6 19:28:21 UTC 2017     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk
$ pkg info fluxbox | grep -i installed
Installed on   : Tue Jan  3 22:44:16 2017 GMT
$ cat /usr/home/bbsadmin-l/.xinitrc 
exec start-lumina-desktop
$  
```

In that environment, user `bbsadmin-l` is not bugged. 

I'll compare with user `grahamperrin` …

**Comment by grahamperrin** [comment] 2017-02-02 05:01
> which other hosts are bugged, I might find one later in the week.

I recognise the 2017-01-13 screenshot under https://gitter.im/trueos/lumina?at=5878fc0adb9cafe9183c72aa as user `grahamperrin` at the same host `momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk`. From that chat: 

> Windows can not be moved by dragging the title bar. … 
> 
> I noticed the problem after accepting Lumina and system defaults. Most recently, system defaults.
> 
> Similarly, windows can not be resized by dragging the handle at bottom right. 
> 
> Alt-Tab no longer working, or not working reliably.

> … No search dialogue in response to Alt-F2. 

> … Hmm I'm sure I keyed Control-C to copy a file name but Control-V in Firefox pastes nothing


I'm more than fifty percent certain that in the two weeks that followed, before I raised this issue, there _was_ at least one incident at another host, but I have not yet *re*produced the issue at four of those five or more hosts. 

If my recollection is wrong – if it's limited to only some user accounts at a single host – then I should treat this issue as very low priority.

**Comment by grahamperrin** [comment] 2017-02-02 07:30
Additional information from a more recent boot environment: 

- windows of applications such as GNOME Web and gedit can be moved and resized. 

For other types of application: 

- bottom right, using the foot of the drag handle (below the triangular, mottled grip) is ineffective
- the mottled area of the drag handle **is** effective, but not apparent in some applications (for example: I see it in SysAdm but not in Firefox). 

```
$ ~/Documents/BSD/TrueOS/about/about

===================
General information
===================

boot loader ………………………………… BSD
            type …………………… EFI
CPU ……………………………………………………… Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
    number of cores …………… 4
host …………………………………………………… momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk
memory ……………………………………………… 16384 MB available, 12332 MB free
OS git branch …………………………………………………………………………………… drm-next
OS git revision ……………………………………………………………………………… 3dbce2a
OS kernel identity ………………………………………… (uname -i) GENERIC
OS platform (architecture) …………………… (uname -m) amd64
OS release level ……………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level … (freebsd-version) 12.0-CURRENT
TrueOS package set ……………… CUSTOM
TrueOS version ………………………… TrueOS-Desktop-201701261715
uptime ……………………………………………… 18 mins
user  ………………………………………………… grahamperrin

More (TrueOS Desktop):

    desktop environment …………… Lumina
    sound card driver ………………… pcm1: <Realtek (0x0280) (Analog 2.0+HP/2.0)> (play/rec) default
    wireless driver ……………………… iwm0
    X11 driver …………………………………… modesetting_drv.so 

$ 
```

I might try SCFB in lieu of KMS.

**Comment by grahamperrin** [comment] 2017-02-02 09:31
> … SCFB in lieu of KMS.

I chose first an Intel driver then SCFB (although re: https://github.com/trueos/trueos-core/issues/316 I'm not certain that the second choice was effective). Also I disabled the compositing manager. None of those experiments resulted in an improvement.

**Comment by utrenkner** [comment] 2017-02-06 13:57
Using FreeBSD 11.0-RELEASE with Lumina at 185699f6, I have the same problem for a few applications with qterminal being the most annyoing - I had to stop using it, as it stayed always on top and there is no way of resizing, moving or pushing in the background.

Interestingly, this problem only occurs after I switch to the (larger) external monitor settings. [As discussed already](https://github.com/trueos/lumina/issues/274), Lumina picks up only the internal screen settings of my ThinkPad T530. After each new login, I have to enable the external screen in order to get the full resolution of the external monitor. But that leads to the problem described by original poster.

I checked that fluxbox is used and that Lumina is started with ``start-lumina-desktop``.

**Comment by utrenkner** [comment] 2017-02-06 14:17
Just tried with the very latest sources (5597b2a2) but that did not change anything with regards to this problem.

**Comment by beanpole135** [comment] 2017-02-27 15:45
OK, it looks like this is something that was reported and possibly fixed in the upcoming version of Fluxbox: https://sourceforge.net/p/fluxbox/bugs/1140/

Along the same lines, could you please run "top" in a terminal (or `ps -auwwx | grep fluxbox`) just to ensure that the Fluxbox process is still running at that time?

**Comment by grahamperrin** [comment] 2017-02-28 20:02
Thanks. 

>> … seems to be 80% reproducible when switching to another workspace … 

Workspace switcher in Lumina appears to have stopped working reliably, so it's hard to describe a set of symptoms but certainly at the time of writing: 

- title bars have disappeared from Firefox and from VLC media player
- neither of the application windows can be resized with Alt-Right click-and-drag. 

>> related for sure: https://sourceforge.net/p/fluxbox/bugs/1111/

– and 1111 suggests that "… file-roller … refuse to … moved, …" but I do _not_ have that problem; the application window _is_ movable. 

```text
$ ps -auwwx | grep fluxbox
grahamperrin 9041   0.0  0.0   14936    2376  2  S+   19:54    0:00.00 grep fluxbox
$ 
```

**Comment by beanpole135** [comment] 2017-03-02 19:02
I just recently found/bypassed a bug in Fluxbox regarding workspace numbering and such which seemed to create the same symptoms mentioned here. Please try rebuilding Lumina from source and see if your  issues are fixed.

https://github.com/trueos/lumina/commit/6dd570e1c1678a2f9709f494f91ab19772638fd5

**Comment by grahamperrin** [comment] 2017-03-03 06:58
Nice work. 

With two workspaces (is that a default?) it does seem that with the bypass I can, in each workspace: 

- move and resize a window of `file-roller` (Archive Manager)
- move and resize a window of Firefox
- move and resize a window of Konsole
- get a 'Search For…'  window in response to Alt-F2
- Control-C copy
- Control-V paste. 

That was last night, at an HP EliteBook 850 G2 notebook with a VGA display to its right, KDE at `ttyv8` and Lumina at `ttyv9`. 

Before closure, for myself I'd like to make the issue (without the bypass) reproducible, to understand whether workspace switching – probably accidental in Lumina – was a key step that I omitted when I opened this issue. 

----

Note to self: for the record but probably unrelated to work on this issue, the integrated display that displayed the panels of Lumina last night was, for one Lumina session this morning, not properly driven (black screen, white non-blinking cursor top left, immovable white arrow pointer around the centre of the area that would be occupied by the display that's on VGA).

**Comment by utrenkner** [comment] 2017-03-05 07:24
Sorry, could not test all week long.

At 0b7d1610, nothing seems to have changed concerning this particular problem. qterminal - and probably a number of other apps - appear without top window frame and are not moveable/resizable.

Fluxbox is still running.

**Comment by grahamperrin** [comment] 2017-03-05 10:54
> … At 0b7d161, nothing seems to have changed concerning this particular problem. … 

Here: 

```text
$ date ; uptime ; pkg info lumina | grep -i version
Sun  5 Mar 2017 10:53:27 GMT
10:53a.m.  up 12 mins, 4 users, load averages: 0.89, 1.60, 1.16
Version        : 201703010628,2
$ 
```

@utrenkner what do you have there?

**Comment by grahamperrin** [comment] 2017-03-05 20:23
Sorry, the symptoms are (again) reproducible with a very recent build of Lumina. 

```text
$ date ; lumina-desktop --version
Sun  5 Mar 2017 20:22:34 GMT
"1.2.1 (Git Revision: 551f993e)"
$ 
```

**Comment by chief1983** [comment] 2017-03-10 14:01
I had the same experience with QTerminal that @utrenkner reported, it is basically completely fixed in place.  This was with a VirtualBox install of the latest available DVD (22 Feb 2017).

**Comment by gvansickle** [comment] 2017-04-08 19:36
I'm in the same situation as @chief1983 , trying to run TrueOS on VirtualBox on Fedora 25.  QTerminal "fixed in place" with no title bar.  On stable repo, up to date as of this writing (Apr 8 2017).  Any news on this issue?  Anything I might be able to do to help?

**Comment by q5sys** [comment] 2017-07-23 12:52
I've been able to reproduce the window with no window border on a Fluxbox only system.  I'm not sure of the root cause, but since it's happening without Lumina installed, it's clearly a Fluxbox issue and not a Lumina issue.

**Closed by q5sys** 2017-07-23 12:52 UTC
