### ISSUE TITLE
Lumina Open not launching processes cleanly?

### ISSUE THREAD

**Issue by q5sys** [trueos/lumina#410] opened 2017-04-12 02:19 UTC
This may be an issue that's lower than Lumina, but I figured I'd start here.  

When using a keyboard shortcut to launch a terminal Lumina-open is used. This is fine, however once the process is started Lumina-open remains around.  Attached photo shows this by launching qterminal, but I've observed the same behavior while launching lumina-fm.  
Process 2422 and 2425 are no longer needed since the processes 2473 and 2431 have successfully started and are running.  

The processes for lumina-open does not need to hang around.  They can be killed without any negative impact on the launched process. (see attached 2nd picture)

Not sure if this is a BSD-ism that I'm unaware of, but it seems like Lumina-open is not getting the signal that the process has launched so it's not quitting.

![not_forking](https://cloud.githubusercontent.com/assets/4654247/24938267/0dd71ed2-1f04-11e7-8df0-6c2fad1b828e.png)
![not_forking2](https://cloud.githubusercontent.com/assets/4654247/24938302/493d552c-1f04-11e7-95f4-13a50d3c17db.png)

**Comment by beanpole135** [comment] 2017-04-12 09:42
Actually, that is by design.
The lumina-open process ID will hand around to monitor the child/application process in order to provide status/crash reporting about it. As soon as the child process is closed, the "parent" lumina-open process will do final checks on it before it too closes (1 to 1 matching between a process and it's watcher).

This behavior **can** be changed by the user right now. There is a file/flag which tells lumina-open to skip all process monitoring, in which case lumina-open will launch the child/app process as a completely detached process and close itself down right after initialization of the child proc. This option/flag corresponds to the "Show application crash data" option under the user preferences in lumina-config.

**Closed by beanpole135** 2017-04-12 09:42 UTC

**Comment by q5sys** [comment] 2017-04-12 13:22
Clever. :)
