### ISSUE TITLE
Create application launcher to run custom command in taskbar panel

### ISSUE THREAD

**Issue by sivamahadevan** [trueos/lumina#417] opened 2017-05-01 16:24 UTC
For example, I would like to create an application launcher (preferrably also with an icon) for "urxvt" on my taskbar panel. However, when I go to Desktop Settings > Panels and add the application launcher to the panel, it doesn't let me write a custom command; instead, it provides a list of installed applications to choose from. Is there any way of doing this?

**Comment by q5sys** [comment] 2017-05-01 21:35
Urxvt isnt registering itself as a XDG application because there is no .desktop file associated with the application.  That's what the panel application launcher is looking for to know what options are available.  This is also the same thing that determines if an application shows up in the application menu or not.

I just committed a graphical utility in Lumina for generating the .desktop files so that you can register applications (like urxvt) in Lumina so that they show up in the applications list as well as within any Lumina utility that gives you a list of potential applications.   That's the short term solution, run it and then move the .desktop file it creates in your home directory to /usr/local/share/applications/
You will also be able to use this utility to register custom shell scripts as a xdg application so that it'll show up in the application menu launcher. 

I'm not going to close this ticket right now, Ken and I talked today about other options on how to tackle this in the future so this ticket will serve as a reminder of that.

**Comment by beanpole135** [comment] 2017-05-02 12:25
Just to follow up with what @q5sys already said:

Long-term solution) 
The **best** solution is for the application (or FreeBSD port) to install an application registration file when the utility is installed - that will fix it showing up on the system for *all* desktop environments and not just Lumina. If you want to use the utility that q5sys just committed to generate the .desktop entry and submit that to the upstream project, then I think that is the best course of action for the long-term.

Short-term solution)
The short term solution is very similar and still requires generating the .desktop file on your own system. Once that file is created, you can put it into "~/.local/share/applications" to register it locally for your user, or in "/usr/local/share/applications" to register it globally for the system.

Background)
The XDG entry specification[1] is one of the foundations of the FreeDesktop standards system and ties into all sorts of various other standards used around the system. We *could* write up bypasses for this standard into individual sections of the Lumina desktop, but that would just open the floodgates for introducing more hacks/bypasses into other subsystems to get around the issues that the XDG entry specification was designed to solve (associating apps with particular file types, localization, icons, etc..) so I would rather not do this unless we have no other choice.

[1] https://standards.freedesktop.org/desktop-entry-spec/latest/

**Closed by beanpole135** 2017-05-02 12:25 UTC
