### ISSUE TITLE
Insight: Paste menu item greyed out when moving files

### ISSUE THREAD

**Issue by scobiehague** [trueos/lumina#339] opened 2016-12-29 18:25 UTC
After clicking 'Copy Selection' on a file or folder, the 'Paste' menu item is greyed out. Pasting a file still works via Ctrl-V or drag-and-drop.

**Comment by q5sys** [comment] 2016-12-30 21:49
I have been unable to reproduce this, can you please open a terminal and enter `lumina-desktop --version` and let me know what version you are using.

**Comment by scobiehague** [comment] 2016-12-30 21:56
1.1.2

**Comment by q5sys** [comment] 2016-12-30 22:33
Thanks for reporting back.
I was on 1.1.0 I think, but I've just built from a newer source tree ("1.1.2 (Git Revision: 67f5289)") and I'm not getting the same behavior.
I recently moved the cut/copy/rename functions back to the main context menu (no longer in a submenu) and that may have resolved this.

**Comment by scobiehague** [comment] 2016-12-31 02:32
This is the version I'm on after running `pc-updatemanager pkgupdate` on STABLE branch:

```
FreeBSD 12.0-CURRENT #11 8b9df91(drm-next-4.7): Sat Dec 24 15:17:28 UTC 2016
```

I've noticed that the 'Paste' selection IS available when I select a file before right-clicking, but this is no good for pasting into empty directories. I'd find is easier to right-click on any free space in the pane to paste.

**Comment by q5sys** [comment] 2016-12-31 18:46
Interestingly, I can reproduce this but ~only~ when the directory view does not include regular files.  If the directory view window has only directories in it, I get the behaviour you are describing.  However if the window has any other type of file in it, the paste option is available without clicking on anything (ie right clicking into free space).  I'll keep digging into this.

**Comment by possnfiffer** [comment] 2017-01-07 19:00
I have TrueOS STABLE branch installed on my work machine and have noticed this issue(the greyed out menu items) even when there are files and folders in the current directory. I found that when I highlight anything(like a file or a folder) in the Insight File Manager, the menu items then begin to work.

**Comment by scobiehague** [comment] 2017-01-07 19:04
Yes this describes my problem. So the only way to copy files to an empty directory would be from the parent directory by highlighting it and selecting paste from the right-click menu.

**Comment by beanpole135** [comment] 2017-01-09 15:47
This was fixed in the Lumina source tree recently. The next push to TrueOS "STABLE" will contain the fix.

**Closed by beanpole135** 2017-01-09 15:47 UTC
Labels: status:investigation
