### ISSUE TITLE
Delayed auto-hiding panel

### ISSUE THREAD

**Issue by q-pa** [trueos/lumina#427] opened 2017-06-06 20:45 UTC
Fresh install of TrueOS-2017-06-01-x64 STABLE on Lenovo Thinkpad T520, 8 GB RAM, using integrated graphics with intel driver.

Before an auto-hiding panel reappears there is a significant delay, first showing an almost empty panel before the full panel appears (see pics).

![panel_1](https://user-images.githubusercontent.com/3322553/26850980-c79c5702-4b09-11e7-823b-187561a6da79.png)
![panel_2](https://user-images.githubusercontent.com/3322553/26850990-d08c660e-4b09-11e7-8cd1-bfb61dbb5769.png)

**Comment by q5sys** [comment] 2017-06-17 00:29
I've been able to reproduce this. After talking it over with Ken we believe it's a fluxbox issue, but, I'll try to poke around some more and see if I can figure anything else out.

**Comment by q5sys** [comment] 2017-07-23 12:15
Are you still having this issue?  I was able to reproduce it once, but the delay was only a fraction of a second.  When talking with Ken about it, we are definitely leaning in the direction that it's Fluxbox misbehaving.

**Comment by q-pa** [comment] 2017-07-23 13:59
Theoretically, this is still an "issue". For a fraction of a second I can see the blank panel with the text Lumina, then the actual panel appears. It does not annoy me anymore. :)

**Comment by q5sys** [comment] 2017-07-28 22:34
Since this is a fluxbox issue and there is nothing we can do about this, I'm going to close this ticket since it no longer annoys you. :P  It wont be an issue with the new window manager... and on the off chance that it is, we can re-open the ticket.

**Closed by q5sys** 2017-07-28 22:34 UTC
Labels: status:investigation
