### ISSUE TITLE
Lumina Search: add "no live" search mode to accelerate searches and spare system resources. Hint about a further acceleration possibility.

### ISSUE THREAD

**Issue by BlazeTester** [trueos/lumina#314] opened 2016-11-24 20:37 UTC
(Searches were performed on TrueOS-Desktop-2016-10-28 installed in VirtualBox.
In the processor menu of VirtualBox, I allocated all 4 Threads of an Intel Core i5-2415M with 2 Cores 4 Threads at 2,3 GHz to guest operating system TrueOS.
In the motherboard menu of VirtualBox, I allocated 2048 MB RAM to guest operating system TrueOS).

Example:
I open Insight File Manager, change into root directory /, and open Lumina Search by "File > Search Directory..".
Then I perform a search for filename crontab in the root directory /

Case A:
When I start entering the characters of the word crontab, only the "c" can be written, because Lumina Search starts searching for the character "c" immediately so that its input field becomes unresponsive due to RAM and CPU stress.
So this way a search for filename crontab in the root directory isn't achievable.

Case B:
I start Lumina Text Editor, type the word crontab, and copy and paste it into Lumina Search's search mask.
Now Lumina Search searches for the desired complete filename from the beginning so that the search is achievable; additionally the RAM and CPU utilization is much lower.

So I recommend the creation of a "no live" search mode in that I can type a search word completely and Lumina Search only starts searching after pressing the enter key on the keyboard. 

Furthermore maybe it's possible to accelerate Lumina Search even more:
The search application "Find any File" for OSX performs very fast searches as it uses "the file system driver's fast search operations".
Further details can be read in the paragraph "What kind of disks do support "fast search"?" on
http://apps.tempel.org/FindAnyFile/support.php
Possibly Lumina Search can perform fast searches on file system ZFS in a similar way as "Find any File" can do it on file system HFS.

**Comment by q5sys** [comment] 2016-11-24 20:58
Just to be sure this was not an issue being created by Virtualbox I tested this on two physical machines and can confirm this behavior.  To add to this as well, if you close the search box (I did so via the panel), the lumina-search process continues to run in the background.  We should probably build a method to kill the search subprocess when the search box is closed. Closing Insight causes the system to lock up for about 10 seconds, but the lumina-search process continues to run in the background.  Eventually the lumina-search process will consume all available RAM (8gb on these machines) until the system becomes almost fully unresponsive.  It took several seconds after a kill -9 on lumina-search to make the system usable again. (I assume memory cleanup operations were themselves being hindered).

**Comment by BlazeTester** [comment] 2016-11-26 15:06
Out of curiosity - on my HFS+ partition with OSX - I used "Find any File" to perform a search for all files/folders that contain the character c in their name.
As "Find any File" can use the file system driver's fast search operations to search within the Catalog File of the HFS+ partition, this search was finished after 1 minute 56 seconds and found 197524 items.

"Find any File" shows the search results (in a separate window) only after a search has been finished completely.
To spare system resources, this time "Find any File" didn't show the search results automatically but displayed a warning that the number of found items is so great that showing all of them could take a long time. That warning window offered the additional options "Show only 20000 items" and "Cancel".
So I recommend that Lumina Search also adopts this kind of behavior so that it can stay responsive itself if many files are found.

**Comment by beanpole135** [comment] 2016-11-28 12:54
Ok, I think I found the cause of the problem - the /proc direcectory heirarchy is actually recursive in nature itself, so the search algorithm is basically looping around in the proc directories.
I will get those dir(s) auto-skipped here soon, and I will look into a better method for stopping the search proc as well (I can confirm that the background process keeps going after closing the lumina-search UI)

**Comment by beanpole135** [comment] 2016-11-28 13:12
Ok, I think I got those things worked out now.
There is a big "stop" button to the right of the search bar while a search is running as well - that will stop the search right then if you need it.

https://github.com/trueos/lumina/commit/102f7c729e55ae92b1bb4b0928dde030a2766b79

**Closed by beanpole135** 2016-11-28 13:12 UTC
