### ISSUE TITLE
OT: Recommended tools to go along with Lumina?

### ISSUE THREAD

**Issue by utrenkner** [trueos/lumina#275] opened 2016-09-26 13:47 UTC
This is another pet peeve of mine: After having worked with Gnome for many years, I find it difficult to find suitable replacement tools for Lumina. I fully appreciate and support the idea of a stripped down desktop which does not come with tons of their own tools. But I have difficulties finding utilities which do not suck in QT4 or some version of GTK.

Maybe we could somewhere start a wiki of tools that play well with Lumina in that they do not require a lot of other dependencies. For e-mail or web browsing everyone will have their favorite software already, I assume. But there are a lot of other utilities which people like me were used to "just have" in their DE. 

E.g. after some searching I found graphics/evince-lite as PDF viewer, which is a stripped-down version of Gnome's evince. And archivers/peazip for file (de)compression. But it is tedious to search for good tools and then check their respective list of dependencies.

**Comment by q5sys** [comment] 2016-09-26 14:38
We can create a wiki on github easy enough, that's not really the problem.  The issue is that everyone will expect that a desktop should 'just have' different things.  I dont mean certain programs, but what utilities should be included.  With so many desktops out there, people have varying ideas of what should be included.  As an old Openbox/LXDE person, I personally feel that a panel, terminal, and file manager should be it.  
The one thing to be careful of going forward is that whatever list is made doesn't morph into a list of 'blessed programs', ie... the ones you 'should' be using.   I think that's why you dont see lists like this in general in the BSDs.  In the end any list that would be made would simply be a trimmed down list of what's available in the ports tree... and it would probably reflect the likes/dislikes of the people making the list.  As such, it would probably exclude software that some people really like and consider a must have. 
It almost sounds like what you'd like is a better way to search the ports tree for additional software; but that's somewhat out of our perview.  If you dont mind me asking, what exact utilities did you find lacking in Lumina?

**Comment by beanpole135** [comment] 2016-09-26 14:46
Welcome to the club... :-)

"Pure" Qt5 apps are actually rather hard to find - most of them have been consumed within the KDE infrastructure and easily install 200+MB of extra KDE libraries and packages which are not really needed by the application. That is actually why I created a few of the Lumina utilities like the text editor and the file manager - simply because those were "essential tools" where I could not find any Qt5 replacement. 

Since we have been searching for the same things for TrueOS, here are a few of the applications we found - but please note that many of them are lacking features or functionality which are commonly available in other main-line applications - it just depends what you want to use and how much functionality is actually "essential" for your workflow:

Email: "trojita" (hosted by KDE, but does not install/use anything from KDE)
Web Browser: Qupzilla or Otter Browser
Terminal Emulator: qterminal
Photo viewer/manager: phototonic

**Comment by utrenkner** [comment] 2016-09-28 11:42
@q5sys It is not that I find anything "lacking" from Lumina in the sense that Lumina should provide it! Again, I absolutely love the idea that Lumina is really just a basic DE and everyone can install their own preferred apps alongside it. 

I already gave two examples: a PDF viewer, a file (de)compression tool, maybe a calculator... Ken gave another good example: a terminal emulator (and I just istalled qterminal - thanks!). Generally, _small_ apps that most of us use more or less regularly. And which usually come bundled with one of the big DEs so that we never learned which other tools are out there, without all those DE-related dependencies.

Another thing I have learned to take for granted from Gnome (and KDE has it too, IIRC): An ssh-agent which is present in the DE so that I do not have to re-type my SSH key password over and over again - even across different terminal windows. I really hate that I do not know how to get the same functionality in Lumina.

**Comment by WoefulDerelict** [comment] 2016-09-28 12:24
@utrenkner ssh-agent is the default agent and is generally included with OpenSSH. Sadly, by providing a prerolled solution you didn't have to configure on your own GNOME does you quite a disservice. In my own personal experience with GNOME I find this behaviour annoying as their ssh-agent doesn't support all the key types and you have to disable and replace it if you use these and need it to actually work.

Perhaps instead of a list of helpful applications what you could really use is a sort of guidebook to getting around in the new environment. In the mean time you may find this section of an article from the Arch Wiki on SSH Keys concerning ssh-agents informative and helpful in playing with the default agent (https://wiki.archlinux.org/index.php/SSH_keys#SSH_agents). Just be glad you don't have to tangle with systemd.

**Comment by utrenkner** [comment] 2016-09-29 12:27
@WoefulDerelict Excellent tipp! I did not know that one could put a ssh-agent line in .xinitrc. Very helpful.

**Comment by beanpole135** [comment] 2016-10-11 13:09
Closing this issue since it is not technically an "issue" with Lumina. 
Feel free to continue offering suggestions here, or join us on the "gitter" chat room for additional information.

**Closed by beanpole135** 2016-10-11 13:09 UTC
