### ISSUE TITLE
Improvement: Allow to save my profile (panels settings)

### ISSUE THREAD

**Issue by bmin** [trueos/lumina#438] opened 2017-07-01 21:02 UTC
Currently there is an option, which is disabled now, "Import". I guess its there to import panels configuration.
I am expecting to save my panels settings so that can be load or share later on.

**Comment by q5sys** [comment] 2017-07-23 12:13
I'll look into this, when I get time.  I thought we already had enabled this.  But if not, then we need to.

**Comment by Mrt134** [comment] 2017-09-18 13:58
Closing this as a duplicate of https://github.com/trueos/lumina/issues/355 - the work is close to done.

**Closed by Mrt134** 2017-09-18 13:58 UTC
Labels: status: on roadmap, status:investigation, type:duplicate, Type:enhancement
