### ISSUE TITLE
Ownership of config files

### ISSUE THREAD

**Issue by q-pa** [trueos/lumina#426] opened 2017-06-06 20:35 UTC
Fresh install of TrueOS-2017-06-01-x64 STABLE on Lenovo Thinkpad T520, using integrated graphics with intel driver.

I had to `chown` the owner  of the files lumina-fm.conf, lumina-open.conf, PCBSD.conf, Qt5Project.conf and lumina-textedit.conf from root to "user" to make changes in the settings persistent (actually, I only applied changes to lumina-fm.conf). 

After opening lumina-fm with `pc-su lumina-fm` and working on root files the owner of lumina-fm.conf and lumina-textedit.conf were automatically set back to root. Starting them with the normal user does not change the owner back.

**Comment by beanpole135** [comment] 2017-06-08 01:29
I just fixed this:
Since the QSettings class was not smart enough to take ownership of the file into consideration, I wrote a quick verification/loading function so that a "root" process (with all the user's directories still selected) will now use a different configuration file than the user processes in order to prevent the root permissions from trashing the user config file.
I already moved all the core/desktop utilities over to using this function when loading their settings files and it seems to be working great so far.

https://github.com/trueos/lumina/commit/0f7668f6cca05f0dae33b94b9178aa4a5e328edc

**Comment by beanpole135** [comment] 2017-06-08 01:30
Oh - Note that this cannot fix the damage already caused by the root process - you will need to `chown` any impacted files back to your user in order to resume saving settings when running the utilities as your user account.

**Comment by q-pa** [comment] 2017-09-03 17:57
I switched to UNSTABLE yesterday. Now this issue has re-appeared in some new form. When I launch lumina-fm as root AND change the icon size than the file lumina-fm.conf gets changed to owner root. If I just e.g. navigate to directories with lumina-fm as root the owner of the file lumina-fm.conf is not changed.
By the way, changes to the icon size are not persistent with root lumina-fm.

**Comment by Mrt134** [comment] 2017-09-05 12:14
Thanks for the update, we'll take a look.

**Comment by ZackaryWelch** [comment] 2017-09-07 21:43
Thanks for clarifying on the cause of the issue. I have reproduced this. When changes are made to the config file with lumina-fm run as root, instead lumina-fm.conf is changed and ownership is given to root, instead of lumina-fm_root.conf being changed. This will be fixed to use the correct configuration file.

**Closed** 2017-09-07 22:11 UTC
